import type { Metadata } from "next";
import { Inter,Playfair_Display } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";

const inter = Playfair_Display({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}><Providers>{children}</Providers></body>
    </html>
  );
}
